// vue/greek-mythology/src/components/Card.vue
<template>
    <div class="card god-card">
        <div class="card-body">
            <h5 class="card-title">{{god.name}}</h5>
            <p class="card-text">{{god.desc}}</p>
        </div>
    </div>
</template>

<script>
export default {
  name: 'Card',
  props: ['god']
}
</script>

<style type="text/css">
    .god-card{
        width: 18rem;
    }
</style>

// angular/greek-mythology/src/app/card/card.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {GodsModel} from "../base/gods.model";

@Component({
  selector: 'card-component',
  templateUrl: './card.component.html',
  styleUrls: ['./card.component.css']
})
export class CardComponent implements OnInit {

  @Input('god') god: GodsModel;

  constructor() {
  }

  ngOnInit() {
  }

}

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">{{god.name}}</h5>
    <p class="card-text">{{god.desc}}</p>
  </div>
</div>
