// vue/greek-mythology/src/components/Base.vue
<template>
  <div id="app">
    <div class="container" v-bind:style="{'padding-top': 15 + 'px'}">
      <card v-for="(god, index) in gods" v-bind:god="god" v-bind:index="index" v-bind:key="index"></card>
    </div>
  </div>
</template>

<script>
import Card from "./Card";
import GreekGods from '../../public/greek-gods.json';

export default {
  name: 'Base',
  data: function() {
    return {
    gods: GreekGods
    }
  },
  components: {
    Card
  }
};
</script>

// react/greek-mythology/src/base/Base.js
/*
 * @Author: Apoorv Vardhan 
 * @Date: 2019-09-21 20:36:13 
 * @Last Modified by: Apoorv Vardhan
 * @Last Modified time: 2019-09-21 20:36:46
 */
import React from "react";
import Card from "../card/Card";
import GreekGods from '../../public/greek-gods.json';

function Base() {
  return (
    <div className="container" style={{paddingTop: 15}}>
      {GreekGods.map((god, index) => {
        return <Card key={index} god={god} />;
      })}
    </div>
  );
}

export default Base;
